### ISSUE TITLE
Problem with `inline`

### ISSUE THREAD

**Issue by markuspf** [gap-packages/cvec#6] opened 2016-10-18 09:13 UTC
On my `stable-4.8` and `master` branches, if I compile `cvec-2.5.5` and try a computation with `fining`, I get

```
#I  Computing adjusted stabilizer chain...
/home/makx/ac/gap-stable/pkg/cvec-2.5.5/bin/x86_64-unknown-dragonfly4.7-gcc-default64/cvec.so: Undefined symbol "INIT_SEQ_ACCESS"
```

`INIT_SEQ_ACCESS` is defined `inline`.

**Comment by markuspf** [comment] 2016-10-18 09:17
Deleting the `inline` from the `#define INLINE inline` "solves" the problem.

**Comment by markuspf** [comment] 2016-10-18 09:19
Sorry for the spam, this is on DragonFly 4.7-dev with 

```
# gcc --version
gcc 5.4.1 [DragonFly] Release/2016-08-27
#  ld --version
GNU gold (GNU Binutils 2.25.1) 1.11
```

So it could be that the compiler/linker are doing something daft.

**Comment by markuspf** [comment] 2016-10-18 09:25
This does not happen on our cloud ubuntu machine with

```
# gcc --version
gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
# ld --version
GNU ld (GNU Binutils for Ubuntu) 2.25.1
```

**Comment by fingolfin** [comment] 2016-10-18 11:13
Looks like a compiler or linker bug at first glance, as `INIT_SEQ_ACCESS` is defined in, and only used in,`src/cvec.c` (ignore `src/quarry.c`, that file is not being compiled). So it appears in a single compilation unit. Hence if the compiler decides to inline it, no trace of it should remain for the linker to even see, let alone complain about. But let's dig some more...

Does it also help if you remove the INLINE from `INLINE void INIT_SEQ_ACCESS` in line 358?

**Comment by markuspf** [comment] 2016-10-18 12:13
Yes, that helps to. It escapes me why the linker would even try to access this symbol at all. I think I can use GNU ld instead of gold. I'll try that first.

**Comment by fingolfin** [comment] 2016-11-06 13:41
Any news on this?

**Comment by fingolfin** [comment] 2017-09-19 17:29
Closing this for now. If you have any new information, feel free to reopen.

**Comment by alex-konovalov** [comment] 2018-06-04 23:16
I can see this now again in the Docker container after the switch to bionic: https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/jobs/387912450

**Comment by fingolfin** [comment] 2018-06-05 06:35
Hmm, still weird I wonder if it helps to change the #define to this: ` #define INLINE static inline`

**Comment by alex-konovalov** [comment] 2018-06-05 10:49
@fingolfin then compilation fails:
```
src/cvec.c:818:1: error: duplicate 'static'
 static INLINE void ADD2_INL(Word *vv,Word *ww,Obj f,long i)
 ^~~~~~
src/cvec.c:844:1: error: duplicate 'static'
 static INLINE void ADD3_INL(Word *uu,Word *vv,Word *ww,Obj f,long i)
 ^~~~~~
...
```

**Comment by fingolfin** [comment] 2018-06-05 10:52
Then change line 362 from
```C
INLINE void INIT_SEQ_ACCESS(seqaccess *sa, Obj v, Int pos)
```
to
```C
static INLINE void INIT_SEQ_ACCESS(seqaccess *sa, Obj v, Int pos)
```

**Comment by alex-konovalov** [comment] 2018-06-05 10:54
It compiles if I add `static` into

    static INLINE void INIT_SEQ_ACCESS(seqaccess *sa, Obj v, Int pos)

- testing now.

**Comment by alex-konovalov** [comment] 2018-06-05 11:00
Yep, I came to the same conclusion. cvec tests now pass. I am looking at other packages that failed in [this build](https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/builds/387912434) to see if this may be connected.

**Comment by fingolfin** [comment] 2018-06-05 11:01
This still sounds like a bug in the linker, though... What does `ld --version` say?

**Comment by alex-konovalov** [comment] 2018-06-05 12:50
Aha, it fixes fining, but not the rest of the packages https://github.com/gap-system/gap-docker/issues/18

**Comment by alex-konovalov** [comment] 2018-06-05 12:59
`ld --version` says:

    GNU ld (GNU Binutils for Ubuntu) 2.30

**Comment by fingolfin** [comment] 2018-06-05 14:12
As to `nq`, the issue is caused by two things: first off, the `lpres` package installs another method for `NilpotentQuotient` but at a lower priority:
```gap
InstallOtherMethod( NilpotentQuotient,
  "for an FpGroup using the LPRES-package", true,
  [ IsFpGroup, IsPosInt ], -1, # give priority to NQ package
  function( G, c )
  return( NilpotentQuotient( Range( IsomorphismLpGroup( G ) ), c ) );
  end);
```
If you just load nq and lpres, there is no problem.

But if you first load nq; then load e.g. semigroups, then load lpres, suddenly the `lpres` method for `NilpotentQuotient` -- because semigroups installs implications for `IsFpGroup`, which increases the rank of `IsFpGroup`, which increases the rank of  the above `NilpotentQuotient` at the moment it is installed...

So a quick workaround would be to change the -1 above to a lower value. In plain GAP, it has a value of 38. After `LoadAllPackages` it has rank 111; so we'd need at least something like -80 or so to make it "safe", but of course if enough implications for `IsFpGroup` is installed, any fixed rank adjustment could become too small.

So this is just a bandaid. The real issue here is that the rank of filters can change, but we never adjust the rank of methods based on that, once they have been installed... 
Of course we could in theory reorder all methods of all operations whenever a new implication is installed, but that's a lot of effort, and I am not sure it's really a good idea... Hrm...

**Comment by alex-konovalov** [comment] 2018-06-05 15:16
I have now understand what happened regarding NQ (although this should be better described elsewhere). It's semigroups package - prior to the update of the Docker container, the version of gcc there was too old and semigroups did not build. Now it is built, and problems became visible.

For cvec, ls is version 2.30 - does this provide any useful inputs?

Not all packages listed at https://github.com/gap-system/gap-docker/issues/18 fail due to Semigroups though, and I still do not know the reason for a couple of them...

**Comment by fingolfin** [comment] 2018-06-07 10:06
The ld version is different from what I have (that's GNU ld 2.26.1), so at least that leaves the possibility for a bug...

In any case, if adding that `static` helps, let's just do that, and make a new release soon.

**Closed** 2018-06-07 10:07 UTC

**Comment by alex-konovalov** [comment] 2018-06-14 09:14
Very good - now tests pass at https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/jobs/392042841
