### ISSUE TITLE
Test suite (builtin/matmul.tst) fails with "CVEC_PROD_CMAT_CMAT: incompatible base fields"

### ISSUE THREAD

**Issue by jasontibbitts** [gap-packages/cvec#19] opened 2018-12-19 00:36 UTC
Please forgive me for knowing basically nothing about GAP, but I am an admin trying to provide a Fedora package of cvec for a user here.  Everything seems fine except that there's a test suite failure I don't understand:
```
gap> Architecture: x86_64-redhat-linux-gnu-gcc-default64

test file         GAP4stones     time(msec)
-------------------------------------------
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/polynomials.tst
polynomials.tst            0           2152
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/echelon.tst
echelon.tst                0              7
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/conversion.tst
conversion.tst             0              2
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/builtin/slice.tst
builtin/slice.tst          0           1695
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/builtin/scalar_unpack.tst
builtin/scalar_unpack.tst       0           9893
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/builtin/scalar_out.tst
builtin/scalar_out.tst       0           8752
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/builtin/scalar_in.tst
builtin/scalar_in.tst       0           6858
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/builtin/misc.tst
builtin/misc.tst           0            952
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/builtin/matmul.tst
########> Diff in /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//\
usr/lib/gap/pkg/cvec/tst/builtin/matmul.tst, line 10:
# Input is:
CVEC.TEST.COMPRESSED_ALL("MATMUL",CVEC.TEST.MATMUL);
# Expected output:
Testing MATMUL COMPRESSED p=2, d=1 ...
Testing MATMUL COMPRESSED p=2, d=2 ...
Testing MATMUL COMPRESSED p=2, d=3 ...
Testing MATMUL COMPRESSED p=2, d=4 ...
Testing MATMUL COMPRESSED p=2, d=5 ...
Testing MATMUL COMPRESSED p=2, d=6 ...
Testing MATMUL COMPRESSED p=2, d=7 ...
Testing MATMUL COMPRESSED p=2, d=8 ...
Testing MATMUL COMPRESSED p=3, d=1 ...
Testing MATMUL COMPRESSED p=3, d=2 ...
Testing MATMUL COMPRESSED p=3, d=3 ...
Testing MATMUL COMPRESSED p=3, d=4 ...
Testing MATMUL COMPRESSED p=3, d=5 ...
Testing MATMUL COMPRESSED p=5, d=1 ...
Testing MATMUL COMPRESSED p=5, d=2 ...
Testing MATMUL COMPRESSED p=5, d=3 ...
Testing MATMUL COMPRESSED p=7, d=1 ...
Testing MATMUL COMPRESSED p=7, d=2 ...
Testing MATMUL COMPRESSED p=11, d=1 ...
Testing MATMUL COMPRESSED p=11, d=2 ...
Testing MATMUL COMPRESSED p=13, d=1 ...
Testing MATMUL COMPRESSED p=13, d=2 ...
Testing MATMUL COMPRESSED p=17, d=1 ...
Testing MATMUL COMPRESSED p=19, d=1 ...
Testing MATMUL COMPRESSED p=23, d=1 ...
Testing MATMUL COMPRESSED p=29, d=1 ...
Testing MATMUL COMPRESSED p=31, d=1 ...
Testing MATMUL COMPRESSED p=37, d=1 ...
Testing MATMUL COMPRESSED p=41, d=1 ...
Testing MATMUL COMPRESSED p=43, d=1 ...
Testing MATMUL COMPRESSED p=47, d=1 ...
Testing MATMUL COMPRESSED p=53, d=1 ...
Testing MATMUL COMPRESSED p=59, d=1 ...
Testing MATMUL COMPRESSED p=61, d=1 ...
Testing MATMUL COMPRESSED p=67, d=1 ...
Testing MATMUL COMPRESSED p=71, d=1 ...
Testing MATMUL COMPRESSED p=73, d=1 ...
Testing MATMUL COMPRESSED p=79, d=1 ...
Testing MATMUL COMPRESSED p=83, d=1 ...
Testing MATMUL COMPRESSED p=89, d=1 ...
Testing MATMUL COMPRESSED p=97, d=1 ...
Testing MATMUL COMPRESSED p=101, d=1 ...
Testing MATMUL COMPRESSED p=103, d=1 ...
Testing MATMUL COMPRESSED p=107, d=1 ...
Testing MATMUL COMPRESSED p=109, d=1 ...
Testing MATMUL COMPRESSED p=113, d=1 ...
Testing MATMUL COMPRESSED p=127, d=1 ...
Testing MATMUL COMPRESSED p=131, d=1 ...
Testing MATMUL COMPRESSED p=137, d=1 ...
Testing MATMUL COMPRESSED p=139, d=1 ...
Testing MATMUL COMPRESSED p=149, d=1 ...
Testing MATMUL COMPRESSED p=151, d=1 ...
Testing MATMUL COMPRESSED p=157, d=1 ...
Testing MATMUL COMPRESSED p=163, d=1 ...
Testing MATMUL COMPRESSED p=167, d=1 ...
Testing MATMUL COMPRESSED p=173, d=1 ...
Testing MATMUL COMPRESSED p=179, d=1 ...
Testing MATMUL COMPRESSED p=181, d=1 ...
Testing MATMUL COMPRESSED p=191, d=1 ...
Testing MATMUL COMPRESSED p=193, d=1 ...
Testing MATMUL COMPRESSED p=197, d=1 ...
Testing MATMUL COMPRESSED p=199, d=1 ...
Testing MATMUL COMPRESSED p=211, d=1 ...
Testing MATMUL COMPRESSED p=223, d=1 ...
Testing MATMUL COMPRESSED p=227, d=1 ...
Testing MATMUL COMPRESSED p=229, d=1 ...
Testing MATMUL COMPRESSED p=233, d=1 ...
Testing MATMUL COMPRESSED p=239, d=1 ...
Testing MATMUL COMPRESSED p=241, d=1 ...
Testing MATMUL COMPRESSED p=251, d=1 ...
# But found:
Testing MATMUL COMPRESSED p=2, d=1 ...
Testing MATMUL COMPRESSED p=2, d=2 ...
Error, CVEC_PROD_CMAT_CMAT: incompatible base fields
########
builtin/matmul.tst         0            597
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/builtin/cvec.tst
builtin/cvec.tst           0             47
testing: /builddir/build/BUILDROOT/gap-pkg-cvec-2.6.1-1.fc29.x86_64//usr/lib/g\
ap/pkg/cvec/tst/builtin/addmul.tst
builtin/addmul.tst         0            361
-------------------------------------------
total                      1              0

#I  Errors detected while testing
```
I just don't know enough about GAP to have any clue as to what might have gone wrong.  I can of course provide complete compilation info and logs if it would be useful.  This is on Fedora 29, using gap-4.8.8-4.fc29.x86_64, gap-pkg-io-4.5.1-3.fc29.x86_64 and gap-pkg-orb-4.8.0-3.fc29.x86_64.

**Comment by alex-konovalov** [comment] 2018-12-19 12:31
Thanks for the report. While I would be interested to know what precisely goes on here, these Fedora packages are not an official GAP distribution and are provided by a third party. They give you GAP 4.8.8 published in August 2016, and it included IO 4.4.6 and Orb 4.7.6 which were known to work together well at the time of release wrapping. Perhaps the problem comes indeed from mixing together incompatible versions of packages and the core system.

What I would recommend to do for the user who requests a GAP installation is to get the latest (November 2018) release of GAP 4.10.0 from https://www.gap-system.org/Releases/. Download one of the archives, unpack it and run `./configure; make` in the unpacked directory. Then change to the pkg subdirectory and call `../bin/BuildPackages.sh` to run the script which will build most of the packages that require compilation (provided sufficiently many libraries, headers and tools are available).

**Comment by jasontibbitts** [comment] 2018-12-19 20:04
Well, if there is any other information I can provide to tell you precisely what's happening, I'm happy to provide it.  I see that error is output at exactly one place in the code:
```
STATIC Obj CVEC_PROD_CMAT_CMAT_DISPATCH(Obj self, Obj m, Obj n)
{
    /* This function is installed as the multiplication function for cmats.
     * It dispatches very quickly for small matrices and calls back
     * CVEC_PROD_CMAT_CMAT_BIG on the GAP level for bigger matrices
     * to sort out Winograd and so on. It also does the catching of
     * argument errors. */
    Obj clm,cln;
    Obj fi;
    Int max;
    Int dim;
    Obj q;
    Obj res;

    if (ElmPRec(m,RNAM_scaclass) != ElmPRec(n,RNAM_scaclass)) {
        return OurErrorBreakQuit(
             "CVEC_PROD_CMAT_CMAT: incompatible base fields");
    }
[...]
```
If there's some way to get more useful information out of that, I'm happy to do so but I have no idea how.

Now, certainly the packages I'm using are not the "official" GAP distribution, but it is trivial to see exactly what is patched.  There are four applied patches to the base gap distribution:
```
# This patch from Debian rearranges some paths to match Linux conventions.
Patch0:         %{name}-paths.patch
# This patch applies a change from Debian to allow help files to be in gzip
# compressed DVI files, and also adds support for viewing with xdg-open.
Patch1:         %{name}-help.patch
# Filed as an upstream git pull request.  Force use of the 64-bit stat()
# routines to avoid overflow of the inode and size fields.  The functions
# supplied by this patch are used by gap-pkg-io.
Patch2:         %{name}-stat.patch

# Fix some unescaped curly braces in the tools
Patch100:       %{name}-escape.patch
```

The actual patches are:
* https://src.fedoraproject.org/rpms/gap/blob/master/f/gap-paths.patch
* https://src.fedoraproject.org/rpms/gap/blob/master/f/gap-help.patch
* https://src.fedoraproject.org/rpms/gap/blob/master/f/gap-stat.patch
* https://src.fedoraproject.org/rpms/gap/blob/master/f/gap-escape.patch

Of those, I could only see the stat patch as having any possible relevance.  I can do some testing without it if you think it's relevant to the problem.

If you're suggesting that the packaged gap is simply too old, I would agree that it would be nice to have 4.10 (and that's a discussion I need to have with the Fedora package maintainers) but supposedly CVEC works with 4.8.8.  If that's not the case then perhaps PackageInfo.g should be updated.

In any case, having individual builds of GAP just doesn't scale; deployment and management are important and using OS-provided packages is the only reasonable way to push GAP to 150+ desktops.  The users aren't generally comfortable with doing software builds themselves and so that's not really an option.  Simply saying "don't use distro packages" is terribly shortsighted, but if you don't wish to even consider bug reports derived from anything but the latest pristine GAP sources then I suppose that's your decision.

**Comment by alex-konovalov** [comment] 2018-12-20 00:42
Thanks for further details @jasontibbitts. 

First of all, I can not reproduce this issue by dropping cvec 2.6.1 into GAP 4.8.10:

```
$ bin/gap.sh -r
 ┌───────┐   GAP 4.8.10, 15-Jan-2018, build of 2018-01-17 11:42:03 (GMT)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin16.7.0-gcc-7-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.1.0, AtlasRep 1.5.1, AutPGrp 1.8, Browse 1.8.7, CRISP 1.4.4, 
             Cryst 4.1.13, CrystCat 1.1.6, CTblLib 1.2.2, FactInt 1.6.0, FGA 1.3.1, GAPDoc 1.6.1, 
             IO 4.5.1, IRREDSOL 1.4, LAGUNA 3.8.0, Polenta 1.3.8, Polycyclic 2.11, RadiRoot 2.7, 
             ResClasses 4.7.1, Sophus 1.23, SpinSym 1.5, TomLib 1.2.6, utils 0.49
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> TestPackage("cvec");
───────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  orb 4.7.6 (Methods to enumerate orbits)
by Juergen Mueller (http://www.math.rwth-aachen.de/~Juergen.Mueller),
   Max Neunhöffer (http://www-groups.mcs.st-and.ac.uk/~neunhoef), and
   Felix Noeske (http://www.math.rwth-aachen.de/~Felix.Noeske).
Homepage: https://gap-packages.github.io/orb
───────────────────────────────────────────────────────────────────────────────────────────────────────
#I  method installed for Length matches more than one declaration
───────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  cvec 2.6.1 (Compact vectors over finite fields)
by Max Neunhöffer (http://www-groups.mcs.st-and.ac.uk/~neunhoef).
Homepage: https://gap-packages.github.io/cvec
───────────────────────────────────────────────────────────────────────────────────────────────────────
Architecture: x86_64-apple-darwin16.7.0-gcc-7-default64

test file         GAP4stones     time(msec)
-------------------------------------------
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/echelon.tst
echelon.tst                0             11
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/conversion.tst
conversion.tst             0             10
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/polynomials.tst
polynomials.tst            0           2176
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/builtin/scalar_unpack.tst
builtin/scalar_unpack.tst       0          18845
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/builtin/scalar_in.tst
builtin/scalar_in.tst       0          11213
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/builtin/slice.tst
builtin/slice.tst          0           2790
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/builtin/matmul.tst
builtin/matmul.tst         0           5839
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/builtin/misc.tst
builtin/misc.tst           0           1301
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/builtin/scalar_out.tst
builtin/scalar_out.tst       0          17235
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/builtin/cvec.tst
builtin/cvec.tst           0             59
testing: /Users/alexk/gap4r8p10/pkg/cvec-2.6.1/tst/builtin/addmul.tst
builtin/addmul.tst         0            544
-------------------------------------------
total                      1              0

#I  No errors detected while testing
```

This uses orb 4.7.6 from GAP 4.8.10 release, but I have checked that tests also pass with orb 4.8.0. The cvec supplied with GAP 4.8.10 also works fine.The other mentioned package - IO - has the same version as in your installation. The repository version of cvec already requires GAP >= 4.9 so it will not work. 

It may be useful to see the GAP banner to see the full selection of packages that you have installed. But the problem seems to be not in the selection of packages, and I have no suggestions about its source at the moment - maybe cvec authors will be able to help more. The patch that you have mentioned might be a red herring - it speaks about fields but in different meaning, while the error message refers to fields as algebraic structures. BTW, I can't find traces of that patch submitted as a pull request to https://github.com/gap-system/gap/ (although that patch was re-added at some point, and the first version of that patch has been incorporated into GAP; but the second is even not applicable any more, since the codebase evolved).

Note that GAP is a research software, and it evolves quickly - since GAP 4.8, we had two major releases 4.9 and 4.10 with many fixes and new features. Also GAP is redistributed with around 140 packages, some of which extend the functionality or improve performance, but may not be available as packages in Fedora sense. If the intended use of it is for teaching, it will be probably fine to start with GAP 4.8 and explain that this is not the latest release, but for research purposes (which might be the case, as cvec is not the package loaded by default) the recommendation to use the official GAP distribution remains.

What else could be done here to help you:?
- just in case, please send me the GAP banner which displays all details about the system and packages loaded by default
- if Docker container for GAP is of any help: https://hub.docker.com/r/gapsystem/gap-docker/
- I don't know your setup, but perhaps you can make a network installation of GAP to install it once in some path accessible from all desktops?
- if you use JupyterHub to provide an access to Jupyter notebooks running on some other server, then GAP now provides a Jupyter kernel: https://gap-packages.github.io/JupyterKernel/, and you can install latest GAP with all packages on that server.

Does anything of these sound usable?

**Comment by fingolfin** [comment] 2019-02-07 15:01
@jasontibbitts  First off, thanks for your report, and sorry for taking so long to respond, but I did not have time to look into this before. 
@alex-konovalov thanks for acting as first responder, I'll take it from here.

Secondly, please note that there is a reason why we provide bundles of GAP with packages: We have tested these in that combination extensively. If you start mix and matching different package version from different times, then in general I'd not be surprised to see breakage, because we simply don't have the resources to test all potential combinations (I am guessing nobody has them, as the number of combinations quickly grows astronomically).

But now, let's see if we can make some progress  on this.

First remark: I cannot reproduce this issue on several machines. But I've not bothered to test with GAP 4.8, as Alex already did that, and anyway, I don't have time to test a gazillion possible combinations blindly. Let's first try to reduce the search space:

1. Can you reproduce this issue on multiple machines? Or just on one? Have you excluded the possibility of hardware faults, such as faulty RAM?

2. What compiler (exact version!) are you using to compiler GAP and cvec? Is it the same compiler?

3. Please provide the config.log files for both cvec and GAP (in the case of GAP 4.8, that's two config.log files, one in the root dir, and one inside `bin/SOME_ARCH_SPECIFIC_DIR/`)

4. In further tests, Please start gap with option `-A` when running the tests, to ensure only a minimal set of packages is loaded, to help us reduce variations.

5. Based on the logs you post, it seems as if the `CVEC.TEST.MATMUL` test for `p=2, d=3` fails. So could you execute that test directly, from an interactive GAP session, and tell us the output? (If those parameters actually work instead of producing a fault, you can of course also try to vary them to see if you can trigger something)
```
LoadPackage("cvec");
CVEC.TEST.MATMUL(2,3);
```

**Comment by fingolfin** [comment] 2019-07-11 13:15
Without further information, there is nothing I can do about this, so I am going to close this now. Feel free to reopen if you have additional information.

**Closed by fingolfin** 2019-07-11 13:15 UTC
